# Generated by Django 2.2.24 on 2021-08-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_price', models.FloatField(verbose_name='Покупка')),
                ('sell_price', models.FloatField(blank=True, null=True, verbose_name='Страйк')),
                ('amount_eth', models.FloatField(blank=True, null=True, verbose_name='ETH')),
                ('opened', models.DateTimeField(auto_now_add=True, verbose_name='Открыт')),
                ('closed', models.DateTimeField(blank=True, max_length=50, null=True, verbose_name='Закрыт')),
                ('active', models.BooleanField(default='True', verbose_name='Активен')),
                ('profit', models.FloatField(blank=True, null=True, verbose_name='Прибыль')),
            ],
            options={
                'verbose_name': 'Позиция',
                'verbose_name_plural': 'Позиции',
                'ordering': ['-opened'],
            },
        ),
        migrations.CreateModel(
            name='Trades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=25, verbose_name='Тип')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('amount_usd', models.FloatField(verbose_name='USD')),
                ('amount_eth', models.FloatField(verbose_name='ETH')),
                ('balance_usd', models.FloatField(verbose_name='Баланс USD')),
                ('balance_eth', models.FloatField(verbose_name='Баланс ETH')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Трейд',
                'verbose_name_plural': 'Трейды',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Variables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_usd', models.FloatField(verbose_name='USD')),
                ('balance_eth', models.FloatField(verbose_name='ETH')),
                ('step', models.FloatField(blank=True, null=True, verbose_name='Шаг позиции USD')),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='Сумма сделки USD')),
                ('profit_percent', models.FloatField(blank=True, null=True, verbose_name='Процент прибыли')),
            ],
            options={
                'verbose_name': 'Переменная',
                'verbose_name_plural': 'Переменные',
            },
        ),
    ]
