# Generated by Django 2.2.24 on 2021-08-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variables',
            name='name',
            field=models.CharField(default='Volat', max_length=250, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
