# Generated by Django 2.2.24 on 2021-08-10 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0004_auto_20210810_2308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strategy',
            options={'verbose_name': 'Стратегия', 'verbose_name_plural': 'Стратегии'},
        ),
        migrations.AddField(
            model_name='position',
            name='strat',
            field=models.CharField(default='', max_length=250, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trades',
            name='strat',
            field=models.CharField(default='', max_length=250, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
