# Generated by Django 2.2.24 on 2021-08-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0006_auto_20210810_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('text', models.CharField(max_length=2500, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
            },
        ),
        migrations.AlterField(
            model_name='strategy',
            name='exchange',
            field=models.CharField(max_length=250, verbose_name='Биржа'),
        ),
    ]
