# Generated by Django 2.2.24 on 2021-08-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0009_auto_20210812_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='pair',
            field=models.CharField(default='ETH/USDT', max_length=250, verbose_name='Пара'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='strategy',
            name='amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Сумма сделки'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='step',
            field=models.FloatField(blank=True, null=True, verbose_name='Шаг позиции'),
        ),
    ]
