# Generated by Django 2.2.24 on 2021-08-13 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0011_auto_20210812_1957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strategy',
            options={'ordering': ['name'], 'verbose_name': 'Стратегия', 'verbose_name_plural': 'Стратегии'},
        ),
    ]
