# Generated by Django 2.2.24 on 2021-08-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0012_auto_20210813_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(max_length=250, verbose_name='Биржа')),
                ('pair', models.CharField(max_length=25, verbose_name='Пара')),
                ('timestamp', models.IntegerField(verbose_name='Время')),
                ('open', models.DecimalField(decimal_places=4, max_digits=12)),
                ('high', models.DecimalField(decimal_places=4, max_digits=12)),
                ('low', models.DecimalField(decimal_places=4, max_digits=12)),
                ('close', models.DecimalField(decimal_places=4, max_digits=12)),
                ('valume', models.DecimalField(decimal_places=4, max_digits=14)),
            ],
            options={
                'verbose_name': 'Чарт',
                'verbose_name_plural': 'Чарты',
                'ordering': ['timestamp'],
                'unique_together': {('exchange', 'pair', 'timestamp')},
            },
        ),
    ]
