# Generated by Django 2.2.24 on 2021-08-14 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0014_auto_20210813_2341'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Strategy',
            new_name='Variants',
        ),
    ]
