# Generated by Django 2.2.24 on 2021-08-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0015_auto_20210814_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Название')),
                ('status', models.CharField(choices=[('Pending', 'Неактивна'), ('Testing', 'Бэктест'), ('Online', 'Онлайн')], default='Pending', max_length=50, verbose_name='Статус')),
                ('variants', models.CharField(max_length=50, verbose_name='Варианты')),
            ],
            options={
                'verbose_name': 'Стратегия',
                'verbose_name_plural': 'Стратегии',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['timestamp'], 'verbose_name': 'Котировка', 'verbose_name_plural': 'Котировки'},
        ),
        migrations.AlterModelOptions(
            name='variants',
            options={'ordering': ['name'], 'verbose_name': 'Вариант', 'verbose_name_plural': 'Варианты'},
        ),
    ]
