# Generated by Django 2.2.24 on 2021-08-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0016_auto_20210814_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='type',
            field=models.CharField(default='volat', max_length=250, verbose_name='Тип'),
            preserve_default=False,
        ),
    ]
