# Generated by Django 2.2.24 on 2021-08-15 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0017_variants_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='strat',
            new_name='varian',
        ),
    ]
