# Generated by Django 2.2.24 on 2021-08-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0018_auto_20210815_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='varian',
            field=models.CharField(max_length=250, verbose_name='Вариант'),
        ),
    ]
