# Generated by Django 2.2.24 on 2021-08-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0019_auto_20210815_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trades',
            name='amount_eth',
            field=models.DecimalField(decimal_places=4, max_digits=12, null='ETH'),
        ),
        migrations.AlterField(
            model_name='trades',
            name='amount_usd',
            field=models.DecimalField(decimal_places=4, max_digits=12, null='USD'),
        ),
        migrations.AlterField(
            model_name='trades',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=12, null='Цена'),
        ),
    ]
