# Generated by Django 2.2.24 on 2021-08-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0020_auto_20210815_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trades',
            name='amount_eth',
            field=models.DecimalField(decimal_places=6, max_digits=12, null='ETH'),
        ),
    ]
