# Generated by Django 2.2.24 on 2021-08-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0021_auto_20210815_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='amount_eth',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='ETH'),
        ),
        migrations.AlterField(
            model_name='position',
            name='buy_price',
            field=models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Покупка'),
        ),
        migrations.AlterField(
            model_name='position',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='Прибыль'),
        ),
        migrations.AlterField(
            model_name='position',
            name='sell_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='Продажа'),
        ),
        migrations.AlterField(
            model_name='position',
            name='strike',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='Страйк'),
        ),
    ]
