# Generated by Django 2.2.24 on 2021-08-16 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0024_auto_20210815_2310'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='history',
            unique_together=set(),
        ),
    ]
