# Generated by Django 2.2.24 on 2021-08-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0025_auto_20210816_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variants',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='Сумма сделки'),
        ),
        migrations.AlterField(
            model_name='variants',
            name='balance_usd',
            field=models.DecimalField(decimal_places=6, max_digits=12, verbose_name='стартовый USD'),
        ),
        migrations.AlterField(
            model_name='variants',
            name='step',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='Шаг позиции'),
        ),
    ]
