# Generated by Django 2.2.24 on 2021-08-16 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0026_auto_20210817_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variants',
            name='profit_percent',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=12, null=True, verbose_name='Процент прибыли'),
        ),
    ]
