# Generated by Django 2.2.24 on 2021-08-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0027_auto_20210817_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trades',
            name='amount_eth',
            field=models.FloatField(default=0, verbose_name='ETH'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trades',
            name='amount_usd',
            field=models.FloatField(default=0, verbose_name='USD'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trades',
            name='price',
            field=models.FloatField(default=0, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
