# Generated by Django 2.2.24 on 2021-08-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0028_auto_20210817_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trades',
            old_name='strat',
            new_name='varian',
        ),
        migrations.RemoveField(
            model_name='trades',
            name='amount_eth',
        ),
        migrations.RemoveField(
            model_name='trades',
            name='amount_usd',
        ),
        migrations.AddField(
            model_name='trades',
            name='base',
            field=models.FloatField(default=0, verbose_name='Базовая'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trades',
            name='quote',
            field=models.FloatField(default=0, verbose_name='Котировка'),
            preserve_default=False,
        ),
    ]
