# Generated by Django 2.2.24 on 2021-08-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0029_auto_20210817_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='amount_eth',
            field=models.FloatField(blank=True, null=True, verbose_name='ETH'),
        ),
        migrations.AlterField(
            model_name='position',
            name='buy_price',
            field=models.FloatField(verbose_name='Покупка'),
        ),
        migrations.AlterField(
            model_name='position',
            name='profit',
            field=models.FloatField(blank=True, null=True, verbose_name='Прибыль'),
        ),
        migrations.AlterField(
            model_name='position',
            name='sell_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Продажа'),
        ),
        migrations.AlterField(
            model_name='position',
            name='strike',
            field=models.FloatField(blank=True, null=True, verbose_name='Страйк'),
        ),
    ]
