# Generated by Django 2.2.24 on 2021-08-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0030_auto_20210817_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variants',
            name='amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Сумма сделки'),
        ),
        migrations.AlterField(
            model_name='variants',
            name='balance_usd',
            field=models.FloatField(verbose_name='Cтартовый'),
        ),
        migrations.AlterField(
            model_name='variants',
            name='profit_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='Процент прибыли'),
        ),
        migrations.AlterField(
            model_name='variants',
            name='step',
            field=models.FloatField(blank=True, null=True, verbose_name='Шаг позиции'),
        ),
    ]
