# Generated by Django 2.2.24 on 2021-08-17 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0032_auto_20210817_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variants',
            old_name='step',
            new_name='step_perc',
        ),
    ]
