# Generated by Django 2.2.24 on 2021-08-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0033_auto_20210817_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variants',
            name='amount',
        ),
        migrations.AddField(
            model_name='variants',
            name='amount_perc',
            field=models.FloatField(blank=True, null=True, verbose_name='Сумма сделки'),
        ),
    ]
