# Generated by Django 2.2.24 on 2021-08-17 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0035_auto_20210817_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variants',
            old_name='balance_usd',
            new_name='balance',
        ),
    ]
