# Generated by Django 2.2.24 on 2021-08-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0036_auto_20210817_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variants',
            name='amount_perc',
        ),
        migrations.AddField(
            model_name='variants',
            name='deal_perc',
            field=models.FloatField(blank=True, null=True, verbose_name='Процент от баланса на сделку'),
        ),
    ]
