# Generated by Django 2.2.24 on 2021-08-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0037_auto_20210817_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variants',
            name='step_perc',
        ),
        migrations.AddField(
            model_name='variants',
            name='range',
            field=models.FloatField(blank=True, null=True, verbose_name='Коридор %'),
        ),
        migrations.AlterField(
            model_name='variants',
            name='deal_perc',
            field=models.FloatField(blank=True, null=True, verbose_name='Количество ставок'),
        ),
        migrations.AlterField(
            model_name='variants',
            name='limit_orders_buy',
            field=models.BooleanField(default=False, verbose_name='Лимитные ордера'),
        ),
    ]
