# Generated by Django 2.2.24 on 2021-08-17 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0038_auto_20210817_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variants',
            old_name='deal_perc',
            new_name='deals',
        ),
    ]
