# Generated by Django 2.2.24 on 2021-08-17 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0040_auto_20210817_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variants',
            old_name='balance',
            new_name='start_balance',
        ),
    ]
