# Generated by Django 2.2.24 on 2021-08-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0041_auto_20210817_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='stop_loss',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Стоп лосс'),
        ),
        migrations.AlterField(
            model_name='position',
            name='amount_base',
            field=models.FloatField(blank=True, null=True, verbose_name='Кол-во базового'),
        ),
    ]
