# Generated by Django 2.2.24 on 2021-08-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0042_auto_20210818_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='timeframe',
            field=models.CharField(choices=[('1m', '1m'), ('1H', '1H')], default='1m', max_length=25, verbose_name='Таймфрейм'),
            preserve_default=False,
        ),
    ]
