# Generated by Django 2.2.24 on 2021-08-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0044_auto_20210819_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategies',
            name='indicators',
            field=models.CharField(max_length=250, null=True, verbose_name='Индикаторы'),
        ),
    ]
