# Generated by Django 2.2.24 on 2021-08-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0045_strategies_indicators'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='finish',
            field=models.BooleanField(default=False, verbose_name='Выполнена'),
        ),
    ]
