# Generated by Django 2.2.24 on 2021-08-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0046_variants_finish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variants',
            name='deals',
        ),
        migrations.RemoveField(
            model_name='variants',
            name='limit_orders_buy',
        ),
        migrations.RemoveField(
            model_name='variants',
            name='profit_percent',
        ),
        migrations.RemoveField(
            model_name='variants',
            name='range',
        ),
        migrations.RemoveField(
            model_name='variants',
            name='stop_loss',
        ),
        migrations.AddField(
            model_name='variants',
            name='indicators',
            field=models.CharField(max_length=250, null=True, verbose_name='Индикаторы'),
        ),
        migrations.AddField(
            model_name='variants',
            name='settings',
            field=models.CharField(max_length=250, null=True, verbose_name='Настройка'),
        ),
    ]
