# Generated by Django 2.2.24 on 2021-08-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0047_auto_20210824_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Название')),
                ('pair', models.CharField(max_length=25, verbose_name='Пара')),
                ('type', models.CharField(max_length=250, verbose_name='Тип')),
                ('exchange', models.CharField(max_length=250, verbose_name='Биржа')),
                ('start_balance', models.FloatField(verbose_name='Cтартовый')),
                ('settings', models.CharField(max_length=250, null=True, verbose_name='Настройка')),
                ('indicators', models.CharField(max_length=250, null=True, verbose_name='Индикаторы')),
                ('finish', models.BooleanField(default=False, verbose_name='Выполнена')),
            ],
            options={
                'verbose_name': 'Тесты',
                'verbose_name_plural': 'Тесты',
                'ordering': ['name'],
            },
        ),
    ]
