# Generated by Django 2.2.24 on 2021-08-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0048_tests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variants',
            name='indicators',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Индикаторы'),
        ),
        migrations.AlterField(
            model_name='variants',
            name='settings',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Настройка'),
        ),
    ]
