# Generated by Django 2.2.24 on 2021-08-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0050_auto_20210824_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Название'),
        ),
    ]
