# Generated by Django 2.2.24 on 2021-08-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0051_auto_20210824_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='average_profit',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Средняя доходность'),
        ),
        migrations.AddField(
            model_name='variants',
            name='sharp',
            field=models.FloatField(blank=True, null=True, verbose_name='Шарп'),
        ),
    ]
