# Generated by Django 2.2.24 on 2021-08-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0052_auto_20210826_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='month_profit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Доходность'),
        ),
    ]
