# Generated by Django 2.2.24 on 2021-09-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0053_variants_month_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variants',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Название'),
        ),
        migrations.AlterUniqueTogether(
            name='variants',
            unique_together={('name', 'type')},
        ),
    ]
