# Generated by Django 2.2.24 on 2021-09-19 17:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0056_options_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='closed',
            field=models.DateTimeField(null=True, verbose_name='Закрыт'),
        ),
        migrations.AlterField(
            model_name='options',
            name='expiration',
            field=models.DateTimeField(verbose_name='Экспирация'),
        ),
        migrations.AlterField(
            model_name='options',
            name='opened',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Открыт'),
        ),
    ]
