# Generated by Django 2.2.24 on 2021-09-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0057_auto_20210919_2011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='options',
            options={'ordering': ['-opened'], 'verbose_name': 'Опцион', 'verbose_name_plural': 'Опционы'},
        ),
        migrations.AddField(
            model_name='options',
            name='sell_price',
            field=models.FloatField(null=True, verbose_name='Закрытие'),
        ),
    ]
