# Generated by Django 2.2.24 on 2021-09-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0058_auto_20210920_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('varian', models.CharField(max_length=250, verbose_name='Название')),
                ('amount', models.FloatField(verbose_name='Сумма')),
                ('desc', models.CharField(max_length=250, verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'ordering': ['-created'],
            },
        ),
    ]
