# Generated by Django 2.2.24 on 2021-09-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0059_trans'),
    ]

    operations = [
        migrations.AddField(
            model_name='options',
            name='delta',
            field=models.FloatField(blank=True, default=1, verbose_name='Дельта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='position',
            name='closed',
            field=models.DateTimeField(null=True, verbose_name='Закрыт'),
        ),
        migrations.AlterField(
            model_name='position',
            name='opened',
            field=models.DateTimeField(verbose_name='Открыт'),
        ),
    ]
