# Generated by Django 2.2.24 on 2021-09-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0060_auto_20210921_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='closed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Закрыт'),
        ),
    ]
