# Generated by Django 2.2.24 on 2021-09-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0061_auto_20210921_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='opened',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Открыт'),
        ),
        migrations.AlterField(
            model_name='options',
            name='sell_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Закрытие'),
        ),
        migrations.AlterField(
            model_name='position',
            name='closed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Закрыт'),
        ),
    ]
